export type ToolbarModalType = `TOOLBAR_MODAL_${
  | 'NONE'
  | 'RESOURCE'
  | 'FILTER'
  | 'SEARCH'
  | 'CONTRIBUTE'}`;

export const TOOLBAR_MODAL_NONE = 'TOOLBAR_MODAL_NONE';
export const TOOLBAR_MODAL_RESOURCE = 'TOOLBAR_MODAL_RESOURCE';
export const TOOLBAR_MODAL_FILTER = 'TOOLBAR_MODAL_FILTER';
export const TOOLBAR_MODAL_SEARCH = 'TOOLBAR_MODAL_SEARCH';
export const TOOLBAR_MODAL_CONTRIBUTE = 'TOOLBAR_MODAL_CONTRIBUTE';

export type ResourceType = 'WATER' | 'FOOD' | 'FORAGE' | 'BATHROOM';
