name: Cypress Tests

on:
  workflow_dispatch:
  schedule:
    cron: 45 4 1 */1 *

jobs:
  tap_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource_type: [water, food, foraging, bathroom]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn start:cypress
          browser: chrome
          spec: cypress/integration/desktop/tapcheck.${{ matrix.resource_type }}.cy.js
          config-file: cypress.integration.config.mjs
